"""empty message

Revision ID: a83a7e0f9430
Revises: 
Create Date: 2021-03-14 15:05:14.727921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a83a7e0f9430'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcard', sa.Column('average_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flashcard', 'average_rating')
    # ### end Alembic commands ###
